class Autogenerated {
  bool success;
  Null errors;
  List<Data> data;

  Autogenerated({this.success, this.errors, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    errors = json['errors'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['errors'] = this.errors;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String id;
  String accountId;
  String moduleCode;
  int orderNumber;

  Data({this.id, this.accountId, this.moduleCode, this.orderNumber});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    accountId = json['accountId'];
    moduleCode = json['moduleCode'];
    orderNumber = json['orderNumber'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['accountId'] = this.accountId;
    data['moduleCode'] = this.moduleCode;
    data['orderNumber'] = this.orderNumber;
    return data;
  }
}